# Generated by Django 4.2.7 on 2023-12-06 21:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('governate', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=30)),
                ('neighborhood', models.CharField(max_length=40)),
                ('building_no', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.IntegerField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('deadline', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('property_type', models.CharField(choices=[('Shop', 'Shop'), ('House', 'House'), ('Land', 'Land')], max_length=15)),
                ('active', models.BooleanField()),
                ('price', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('offers', models.ManyToManyField(to='base.offer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
