# Generated by Django 6.0.1 on 2026-01-14 21:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=30)),
                ("governate", models.CharField(max_length=20)),
                ("area", models.CharField(max_length=30)),
                ("neighborhood", models.CharField(max_length=40)),
                ("building_no", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Estate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("space", models.IntegerField()),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("deadline", models.DateField()),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Shop", "Shop"),
                            ("House", "House"),
                            ("Land", "Land"),
                        ],
                        max_length=15,
                    ),
                ),
                ("active", models.BooleanField()),
                ("price", models.IntegerField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.address"
                    ),
                ),
            ],
        ),
    ]
