# Generated by Django 6.0.1 on 2026-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_contactinfo_contactmedia_covers_section_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(default="slides/default.jpg", upload_to="slides"),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Covers",
        ),
    ]
