# Generated by Django 6.0.1 on 2026-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_slide_delete_covers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EstateSection",
            new_name="SectionEstate",
        ),
        migrations.RenameField(
            model_name="section",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="section",
            name="estates",
            field=models.ManyToManyField(
                through="base.SectionEstate", to="base.estate"
            ),
        ),
    ]
